const db = require('./conn.js')
const Team = require('./Team')
const Division = require('./Division')
const User = require('./User')

Team.belongsTo(Division)
Division.hasMany(Team)

const syncAndSeed = async () => {
  await db.sync({ force: true })

  const [
    scott,
    chiefs,
    chargers,
    raiders,
    broncos,
    bills,
    dolphins,
    patriots,
    jets,
    bengals,
    browns,
    steelers,
    ravens,
    jaguars,
    texans,
    colts,
    titans,
    niners,
    seahawks,
    rams,
    cardinals,
    eagles,
    cowboys,
    giants,
    commanders,
    vikings,
    lions,
    packers,
    bears,
    buccaneers,
    panthers,
    saints,
    falcons,
    afcWest,
    afcEast,
    afcNorth,
    afcSouth,
    nfcWest,
    nfcEast,
    nfcNorth,
    nfcSouth,
  ] = await Promise.all([
    //// USER ////////
    User.create({
      username: 'Scott',
      password: '123',
    }),
    User.create({
      username: 'test',
      password: '123',
    }),
    //// AFC WEST ////////
    Team.create({
      name: 'CHIEFS',
      divisionName: 'AFC West',
      wins: 14,
      losses: 3,
      avgYdsTotal: 404.6,
      avgYdsPass: 288.9,
      avgYdsRush: 115.7,
      seasonPoints: [
        '44',
        '27',
        '17',
        '41',
        '30',
        '20',
        '44',
        '20',
        '27',
        '30',
        '26',
        '24',
        '34',
        '30',
        '24',
        '27',
        '31',
      ],
      logo: 'chiefs.webp',
      primaryColor: 'rgb(165, 0, 0)',
    }),
    Team.create({
      name: 'CHARGERS',
      divisionName: 'AFC West',
      wins: 10,
      losses: 7,
      avgYdsTotal: 357.1,
      avgYdsPass: 268.7,
      avgYdsRush: 88.4,
      seasonPoints: [
        '24',
        '24',
        '10',
        '34',
        '30',
        '19',
        '23',
        '20',
        '16',
        '27',
        '25',
        '20',
        '23',
        '17',
        '20',
        '31',
        '28',
      ],
      logo: 'chargers.webp',
      primaryColor: 'rgb(0, 125, 202)',
    }),
    Team.create({
      name: 'RAIDERS',
      divisionName: 'AFC West',
      wins: 6,
      losses: 10,
      avgYdsTotal: 352.5,
      avgYdsPass: 231.4,
      avgYdsRush: 121.1,
      seasonPoints: [
        '19',
        '23',
        '22',
        '32',
        '29',
        '38',
        '0',
        '20',
        '20',
        '22',
        '40',
        '27',
        '16',
        '30',
        '10',
        '34',
        '13',
      ],
      logo: 'raiders.webp',
      primaryColor: 'black',
    }),
    Team.create({
      name: 'BRONCOS',
      divisionName: 'AFC West',
      wins: 5,
      losses: 12,
      avgYdsTotal: 325.1,
      avgYdsPass: 211.3,
      avgYdsRush: 113.8,
      seasonPoints: [
        '16',
        '16',
        '11',
        '23',
        '9',
        '16',
        '9',
        '21',
        '10',
        '16',
        '10',
        '9',
        '28',
        '24',
        '14',
        '24',
        '31',
      ],
      logo: 'broncos.webp',
      primaryColor: 'rgb(255, 98, 0)',
    }),
    //// AFC EAST ////////
    Team.create({
      name: 'BILLS',
      divisionName: 'AFC East',
      wins: 13,
      losses: 3,
      avgYdsTotal: 349.9,
      avgYdsPass: 261.4,
      avgYdsRush: 133.5,
      seasonPoints: [
        '31',
        '41',
        '19',
        '23',
        '38',
        '24',
        '27',
        '17',
        '30',
        '31',
        '28',
        '24',
        '20',
        '32',
        '35',
        '35',
      ],
      logo: 'bills.webp',
      primaryColor: 'rgb(25, 43, 156)',
    }),
    Team.create({
      name: 'DOLPHINS',
      divisionName: 'AFC East',
      wins: 9,
      losses: 8,
      avgYdsTotal: 357.1,
      avgYdsPass: 261.1,
      avgYdsRush: 96.0,
      seasonPoints: [
        '20',
        '42',
        '21',
        '15',
        '17',
        '16',
        '16',
        '31',
        '35',
        '39',
        '30',
        '17',
        '17',
        '29',
        '20',
        '21',
        '11',
      ],
      logo: 'dolphins.webp',
      primaryColor: 'teal',
    }),
    Team.create({
      name: 'PATRIOTS',
      divisionName: 'AFC East',
      wins: 8,
      losses: 9,
      avgYdsTotal: 314.6,
      avgYdsPass: 208.0,
      avgYdsRush: 106.6,
      seasonPoints: [
        '7',
        '17',
        '26',
        '24',
        '29',
        '38',
        '14',
        '22',
        '26',
        '10',
        '26',
        '10',
        '27',
        '24',
        '18',
        '23',
        '23',
      ],
      logo: 'patriots.webp',
      primaryColor: 'rgb(25, 37, 97)',
    }),
    Team.create({
      name: 'JETS',
      divisionName: 'AFC East',
      wins: 7,
      losses: 10,
      avgYdsTotal: 318.2,
      avgYdsPass: 219.0,
      avgYdsRush: 99.2,
      seasonPoints: [
        '9',
        '31',
        '12',
        '24',
        '40',
        '27',
        '16',
        '17',
        '20',
        '3',
        '31',
        '22',
        '12',
        '17',
        '3',
        '6',
        '6',
      ],
      logo: 'jets.webp',
      primaryColor: 'rgb(0, 94, 35)',
    }),
    //// AFC NORTH ////////
    Team.create({
      name: 'BENGALS',
      divisionName: 'AFC North',
      wins: 12,
      losses: 4,
      avgYdsTotal: 353.8,
      avgYdsPass: 257.7,
      avgYdsRush: 95.9,
      seasonPoints: [
        '20',
        '17',
        '27',
        '27',
        '17',
        '30',
        '35',
        '13',
        '42',
        '37',
        '20',
        '27',
        '23',
        '34',
        '22',
        '27',
      ],
      logo: 'bengals.webp',
      primaryColor: 'orangered',
    }),
    Team.create({
      name: 'BROWNS',
      divisionName: 'AFC North',
      wins: 7,
      losses: 10,
      avgYdsTotal: 349.1,
      avgYdsPass: 202.6,
      avgYdsRush: 146.5,
      seasonPoints: [
        '26',
        '30',
        '29',
        '20',
        '28',
        '15',
        '20',
        '32',
        '17',
        '23',
        '23',
        '27',
        '10',
        '13',
        '10',
        '24',
        '14',
      ],
      logo: 'browns.webp',
      primaryColor: 'rgb(202, 58, 6)',
    }),
    Team.create({
      name: 'STEELERS',
      divisionName: 'AFC North',
      wins: 9,
      losses: 8,
      avgYdsTotal: 322.6,
      avgYdsPass: 200.6,
      avgYdsRush: 121.9,
      seasonPoints: [
        '23',
        '14',
        '17',
        '20',
        '3',
        '20',
        '10',
        '13',
        '20',
        '30',
        '24',
        '10',
        '14',
        '24',
        '13',
        '16',
        '28',
      ],
      logo: 'steelers.webp',
      primaryColor: 'rgb(215, 162, 0)',
    }),
    Team.create({
      name: 'RAVENS',
      divisionName: 'AFC North',
      wins: 10,
      losses: 7,
      avgYdsTotal: 340.2,
      avgYdsPass: 180.5,
      avgYdsRush: 159.7,
      seasonPoints: [
        '24',
        '38',
        '37',
        '20',
        '19',
        '20',
        '23',
        '27',
        '27',
        '13',
        '27',
        '10',
        '16',
        '3',
        '17',
        '13',
        '16',
      ],
      logo: 'ravens.webp',
      primaryColor: 'rgb(64, 4, 169)',
    }),
    //// AFC SOUTH ////////
    Team.create({
      name: 'JAGUARS',
      divisionName: 'AFC South',
      wins: 9,
      losses: 8,
      avgYdsTotal: 358.6,
      avgYdsPass: 233.5,
      avgYdsRush: 125.1,
      seasonPoints: [
        '22',
        '24',
        '38',
        '21',
        '6',
        '27',
        '17',
        '17',
        '27',
        '17',
        '28',
        '14',
        '36',
        '40',
        '19',
        '31',
        '20',
      ],
      logo: 'jaguars.webp',
      primaryColor: 'teal',
    }),
    Team.create({
      name: 'TEXANS',
      divisionName: 'AFC South',
      wins: 3,
      losses: 13,
      avgYdsTotal: 283.5,
      avgYdsPass: 196.7,
      avgYdsRush: 86.8,
      seasonPoints: [
        '20',
        '9',
        '20',
        '24',
        '13',
        '20',
        '10',
        '17',
        '16',
        '10',
        '15',
        '14',
        '23',
        '24',
        '19',
        '3',
        '32',
      ],
      logo: 'texans.webp',
      primaryColor: 'rgb(26, 30, 70)',
    }),
    Team.create({
      name: 'COLTS',
      divisionName: 'AFC South',
      wins: 4,
      losses: 12,
      avgYdsTotal: 311.6,
      avgYdsPass: 201.9,
      avgYdsRush: 109.8,
      seasonPoints: [
        '20',
        '0',
        '20',
        '17',
        '12',
        '34',
        '10',
        '16',
        '3',
        '25',
        '16',
        '17',
        '19',
        '36',
        '3',
        '10',
        '31',
      ],
      logo: 'colts.webp',
      primaryColor: 'rgb(29, 41, 110)',
    }),
    Team.create({
      name: 'TITANS',
      divisionName: 'AFC South',
      wins: 7,
      losses: 10,
      avgYdsTotal: 296.8,
      avgYdsPass: 171.4,
      avgYdsRush: 125.4,
      seasonPoints: [
        '20',
        '7',
        '24',
        '24',
        '21',
        '19',
        '17',
        '17',
        '17',
        '27',
        '16',
        '10',
        '22',
        '14',
        '14',
        '13',
        '16',
      ],
      logo: 'titans.webp',
      primaryColor: 'rgb(16, 118, 181)',
    }),
    //// NFC WEST ////////
    Team.create({
      name: '49ERS',
      divisionName: 'NFC West',
      wins: 13,
      losses: 4,
      avgYdsTotal: 359.9,
      avgYdsPass: 223.1,
      avgYdsRush: 136.8,
      seasonPoints: [
        '10',
        '27',
        '10',
        '24',
        '37',
        '14',
        '23',
        '31',
        '22',
        '38',
        '13',
        '33',
        '35',
        '21',
        '37',
        '37',
        '18',
      ],
      logo: '49ers.webp',
      primaryColor: 'rgb(215, 162, 0)',
    }),
    Team.create({
      name: 'SEAHAWKS',
      divisionName: 'NFC West',
      wins: 9,
      losses: 8,
      avgYdsTotal: 350.4,
      avgYdsPass: 231.2,
      avgYdsRush: 119.2,
      seasonPoints: [
        '17',
        '7',
        '23',
        '48',
        '32',
        '19',
        '37',
        '27',
        '31',
        '16',
        '34',
        '27',
        '24',
        '13',
        '10',
        '23',
        '19',
      ],
      logo: 'seahawks.webp',
      primaryColor: 'rgb(30, 50, 96)',
    }),
    Team.create({
      name: 'RAMS',
      divisionName: 'NFC West',
      wins: 5,
      losses: 12,
      avgYdsTotal: 280.5,
      avgYdsPass: 182.8,
      avgYdsRush: 97.7,
      seasonPoints: [
        '10',
        '31',
        '20',
        '9',
        '10',
        '24',
        '14',
        '13',
        '17',
        '20',
        '10',
        '23',
        '17',
        '12',
        '51',
        '10',
        '16',
      ],
      logo: 'rams.webp',
      primaryColor: 'rgb(25, 25, 161)',
    }),
    Team.create({
      name: 'CARDINALS',
      divisionName: 'NFC West',
      wins: 5,
      losses: 12,
      avgYdsTotal: 323.5,
      avgYdsPass: 213.3,
      avgYdsRush: 110.2,
      seasonPoints: [
        '21',
        '29',
        '12',
        '16',
        '17',
        '9',
        '42',
        '26',
        '21',
        '27',
        '10',
        '17',
        '15',
        '16',
        '13',
        '19',
        '17',
      ],
      logo: 'cardinals.webp',
      primaryColor: 'rgb(106, 32, 36)',
    }),
    //// NFC EAST ////////
    Team.create({
      name: 'EAGLES',
      divisionName: 'NFC East',
      wins: 14,
      losses: 3,
      avgYdsTotal: 385.8,
      avgYdsPass: 233.8,
      avgYdsRush: 152.0,
      seasonPoints: [
        '38',
        '24',
        '24',
        '29',
        '20',
        '26',
        '35',
        '29',
        '21',
        '17',
        '40',
        '35',
        '48',
        '25',
        '34',
        '10',
        '22',
      ],
      logo: 'eagles.webp',
      primaryColor: 'rgb(0, 92, 92)',
    }),
    Team.create({
      name: 'COWBOYS',
      divisionName: 'NFC East',
      wins: 12,
      losses: 5,
      avgYdsTotal: 354.8,
      avgYdsPass: 223.1,
      avgYdsRush: 131.7,
      seasonPoints: [
        '3',
        '20',
        '23',
        '25',
        '22',
        '17',
        '24',
        '49',
        '28',
        '40',
        '28',
        '54',
        '27',
        '34',
        '40',
        '27',
        '6',
      ],
      logo: 'cowboys.webp',
      primaryColor: 'rgb(25, 37, 97)',
    }),
    Team.create({
      name: 'GIANTS',
      divisionName: 'NFC East',
      wins: 9,
      losses: 7,
      avgYdsTotal: 333.4,
      avgYdsPass: 187.1,
      avgYdsRush: 146.3,
      seasonPoints: [
        '21',
        '19',
        '16',
        '20',
        '27',
        '24',
        '23',
        '13',
        '24',
        '18',
        '20',
        '20',
        '22',
        '20',
        '24',
        '38',
        '16',
      ],
      logo: 'giants.webp',
      primaryColor: 'maroon',
    }),
    Team.create({
      name: 'COMMANDERS',
      divisionName: 'NFC East',
      wins: 8,
      losses: 8,
      avgYdsTotal: 330.3,
      avgYdsPass: 204.2,
      avgYdsRush: 126.1,
      seasonPoints: [
        '28',
        '27',
        '8',
        '10',
        '17',
        '12',
        '23',
        '17',
        '17',
        '32',
        '23',
        '19',
        '34',
        '20',
        '12',
        '20',
        '10',
      ],
      logo: 'commanders.webp',
      primaryColor: 'rgb(77, 14, 17)',
    }),
    //// NFC NORTH ////////
    Team.create({
      name: 'VIKINGS',
      divisionName: 'NFC North',
      wins: 13,
      losses: 4,
      avgYdsTotal: 359.8,
      avgYdsPass: 264.2,
      avgYdsRush: 95.7,
      seasonPoints: [
        '23',
        '7',
        '28',
        '28',
        '29',
        '24',
        '34',
        '20',
        '33',
        '3',
        '33',
        '27',
        '23',
        '39',
        '27',
        '17',
        '29',
      ],
      logo: 'vikings.webp',
      primaryColor: 'rgb(95, 22, 95)',
    }),
    Team.create({
      name: 'LIONS',
      divisionName: 'NFC North',
      wins: 9,
      losses: 8,
      avgYdsTotal: 380,
      avgYdsPass: 251.8,
      avgYdsRush: 128.2,
      seasonPoints: [
        '35',
        '36',
        '24',
        '45',
        '0',
        '6',
        '27',
        '15',
        '31',
        '31',
        '25',
        '40',
        '34',
        '20',
        '23',
        '41',
        '20',
      ],
      logo: 'lions.webp',
      primaryColor: 'rgb(29, 113, 216)',
    }),
    Team.create({
      name: 'PACKERS',
      divisionName: 'NFC North',
      wins: 8,
      losses: 9,
      avgYdsTotal: 337.9,
      avgYdsPass: 213.6,
      avgYdsRush: 124.3,
      seasonPoints: [
        '7',
        '27',
        '14',
        '27',
        '22',
        '10',
        '21',
        '17',
        '9',
        '31',
        '17',
        '33',
        '28',
        '24',
        '26',
        '41',
        '16',
      ],
      logo: 'packers.webp',
      primaryColor: 'rgb(0, 55, 5)',
    }),
    Team.create({
      name: 'BEARS',
      divisionName: 'NFC North',
      wins: 3,
      losses: 14,
      avgYdsTotal: 307.8,
      avgYdsPass: 130.5,
      avgYdsRush: 177.3,
      seasonPoints: [
        '19',
        '10',
        '23',
        '12',
        '22',
        '7',
        '33',
        '29',
        '32',
        '30',
        '24',
        '10',
        '19',
        '20',
        '13',
        '10',
        '13',
      ],
      logo: 'bears.webp',
      primaryColor: 'orangered',
    }),
    //// NFC SOUTH ////////
    Team.create({
      name: 'BUCCANEERS',
      divisionName: 'NFC South',
      wins: 8,
      losses: 9,
      avgYdsTotal: 348.9,
      avgYdsPass: 273.3,
      avgYdsRush: 75.6,
      seasonPoints: [
        '19',
        '20',
        '12',
        '31',
        '21',
        '18',
        '3',
        '22',
        '16',
        '21',
        '17',
        '17',
        '7',
        '23',
        '19',
        '30',
        '17',
      ],
      logo: 'buccaneers.webp',
      primaryColor: 'rgb(125, 20, 34)',
    }),
    Team.create({
      name: 'PANTHERS',
      divisionName: 'NFC South',
      wins: 7,
      losses: 10,
      avgYdsTotal: 306.3,
      avgYdsPass: 176.2,
      avgYdsRush: 130,
      seasonPoints: [
        '24',
        '16',
        '22',
        '16',
        '15',
        '10',
        '21',
        '34',
        '21',
        '25',
        '3',
        '23',
        '30',
        '16',
        '37',
        '24',
        '10',
      ],
      logo: 'panthers.webp',
      primaryColor: 'rgb(15, 127, 220)',
    }),
    Team.create({
      name: 'SAINTS',
      divisionName: 'NFC South',
      wins: 7,
      losses: 10,
      avgYdsTotal: 333.8,
      avgYdsPass: 217.2,
      avgYdsRush: 116.6,
      seasonPoints: [
        '27',
        '10',
        '14',
        '25',
        '39',
        '26',
        '34',
        '24',
        '13',
        '10',
        '27',
        '0',
        '16',
        '21',
        '17',
        '20',
        '7',
      ],
      logo: 'saints.webp',
      primaryColor: 'rgb(195, 182, 110)',
    }),
    Team.create({
      name: 'FALCONS',
      divisionName: 'NFC South',
      wins: 7,
      losses: 10,
      avgYdsTotal: 318.6,
      avgYdsPass: 158.8,
      avgYdsRush: 159.9,
      seasonPoints: [
        '27',
        '10',
        '14',
        '25',
        '39',
        '26',
        '34',
        '24',
        '13',
        '10',
        '27',
        '0',
        '16',
        '21',
        '17',
        '20',
        '7',
      ],
      logo: 'falcons.webp',
      primaryColor: 'black',
    }),
    ////// DIVISIONS /////////////////////////////
    Division.create({
      name: 'AFC West',
    }),
    Division.create({
      name: 'AFC East',
    }),
    Division.create({
      name: 'AFC North',
    }),
    Division.create({
      name: 'AFC South',
    }),
    Division.create({
      name: 'NFC West',
    }),
    Division.create({
      name: 'NFC East',
    }),
    Division.create({
      name: 'NFC North',
    }),
    Division.create({
      name: 'NFC South',
    }),
  ])
  return {
    scott,
    teams: {
      chiefs,
      chargers,
      raiders,
      broncos,
      bills,
      dolphins,
      patriots,
      jets,
      bengals,
      browns,
      steelers,
      ravens,
      jaguars,
      texans,
      colts,
      titans,
      niners,
      seahawks,
      rams,
      cardinals,
      eagles,
      cowboys,
      giants,
      commanders,
      vikings,
      lions,
      packers,
      bears,
      buccaneers,
      panthers,
      saints,
      falcons,
      afcWest,
      afcEast,
      afcNorth,
      afcSouth,
      nfcWest,
      nfcEast,
      nfcNorth,
      nfcSouth,
    },
  }
}

module.exports = {
  syncAndSeed,
  db,
  User,
  Team,
  Division,
}
